version: '2.15.1'

services:
  tinyauth:
    build: ./
    command: ./authapi db
    ports:
      - 6969:8080
    depends_on:
      - db

  db:
    restart: always
    image: postgres:latest
    volumes:
      - .\pg:/var/lib/postgresql
      - .\.database\postgres\data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    command: /bin/sh -c "/var/lib/postgresql/pginit.sh"
    ports:
      - 5436:5432